name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
          cache: 'pnpm'
      - name: Step 1 - Echo out a GitHub Actions Secret to the logs
        run: |
          echo "The GitHub Action Secret will be masked:  "
          echo ${{ secrets.CF_API_TOKEN }}
          echo "Trick to echo GitHub Actions Secret:  "
          echo ${{secrets.CF_ACCOUNT_ID}} | sed 's/./& /g' 
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Publish
        run: pnpm deploy
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CF_ACCOUNT_ID }}
